### ISSUE TITLE
RuntimeError: Failed to load audio

### ISSUE THREAD

**Issue by edsu** [sul-dlss/speech-to-text#59]
I noticed this exception in `speech-to-text.py`. I believe it occurred when Whisper is trying to transcribe `qw921qz8979-v2/wz891rq8670_sl.mp4` in [qw921qz8979](https://argo-qa.stanford.edu/view/qw921qz8979). I think the error is saying that the MP4 file lacks an audio track?

I'm confused about how `NameError: name 'SpeechToTextException' is not defined` is getting throw as the class is clearly defined? The docker container completely exited after the error.

```
2024-12-05T02:40:39+0000 :: INFO :: starting job {'id': 'qw921qz8979-v2', 'druid': 'druid:qw921qz8979', 'media': [{'name': 'qw921qz8979-v2/wz891rq8670_sl.mp4'}], 'options': {'model': 'large-v3', 'beam_size': 10, 'writer': {'max_line_width': 42, 'max_line_count': 1}}}
2024-12-05T02:40:40+0000 :: INFO :: downloaded qw921qz8979-v2/wz891rq8670_sl.mp4: {"duration": 445.312, "format": "mov,mp4,m4a,
3gp,3g2,mj2", "size": 55895540}
2024-12-05T02:40:40+0000 :: INFO :: running whisper on qw921qz8979-v2/wz891rq8670_sl.mp4 with model=large-v3 options={'beam_siz
e': 10, 'word_timestamps': True}
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/whisper/audio.py", line 58, in load_audio
    out = run(cmd, capture_output=True, check=True).stdout
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 569, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ffmpeg', '-nostdin', '-threads', '0', '-i', 'qw921qz8979-v2/wz891rq8670_sl.mp4', '-f'
, 's16le', '-ac', '1', '-acodec', 'pcm_s16le', '-ar', '16000', '-']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/speech_to_text.py", line 142, in run_whisper
    result = whisper.transcribe(
             ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/whisper/transcribe.py", line 133, in transcribe
    mel = log_mel_spectrogram(audio, model.dims.n_mels, padding=N_SAMPLES)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/whisper/audio.py", line 140, in log_mel_spectrogram
    audio = load_audio(audio)
            ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/whisper/audio.py", line 60, in load_audio
    raise RuntimeError(f"Failed to load audio: {e.stderr.decode()}") from e
RuntimeError: Failed to load audio: ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdi
r=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom -
-enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --ena
ble-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack -
-enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-libr
abbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable
-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable
-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable
-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394
 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'qw921qz8979-v2/wz891rq8670_sl.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.20.100
  Duration: 00:07:25.31, start: 0.000000, bitrate: 1004 kb/s
  Stream #0:0(eng): Video: h264 (Main) (avc1 / 0x31637661), yuv420p, 640x480 [SAR 1:1 DAR 4:3], 1001 kb/s, 29.97 fps, 29.97 tbr
, 11988 tbn, 59.94 tbc (default)
    Metadata:
      handler_name    : Video Media Handler
      vendor_id       : [0][0][0][0]
Output #0, s16le, to 'pipe:':
Output file #0 does not contain any stream


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/speech_to_text.py", line 36, in main
    job = run_whisper(job)
          ^^^^^^^^^^^^^^^^
  File "/app/speech_to_text.py", line 150, in run_whisper
    raise SpeechToTextException(str(e))
          ^^^^^^^^^^^^^^^^^^^^^
NameError: name 'SpeechToTextException' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/speech_to_text.py", line 436, in <module>
    main(daemon=args.daemon)
  File "/app/speech_to_text.py", line 43, in main
    except SpeechToTextException as e:
           ^^^^^^^^^^^^^^^^^^^^^
NameError: name 'SpeechToTextException' is not defined
```

**Comment by edsu** [comment]
We talked about this a bit in standup, and decided we needed @andrewjbtw to be there to help decide how to move forward. We got talking about if an Item has multiple media files, and one of them lacks audio should we skip it (like in ocrWF) or should we fail the whole job?

**Comment by andrewjbtw** [comment]
I think we should skip it rather than fail the whole job. We could try to work out a way for a user to re-send the job with the silent item(s) excluded, but that seems like a lot of complication for the user interface.

If we had a place to report which items got processed and which were skipped, I would note it there, but I'm not sure where we could provide that report.

**Comment by edsu** [comment]
Ok. The speech-to-text service returns a block of JSON indicating what processing was done. This would be empty in the case of an item with one media file, or missing run information for the particular media file if there was more than one. We have talked about the watcher daemon throw this information at the Event service when it hears back the speech-to-text service, but I'm not sure if that's ticketed.

**Comment by edsu** [comment]
I guess we could simply return an error if the media lacks audio, and leave it up to common-accessioning to decide what does and does not get sent?
